# Generated by Django 4.0.3 on 2023-03-29 15:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodyweight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyvideo', models.FileField(upload_to='bodyworkoutpost', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('title', models.TextField()),
                ('viewss', models.IntegerField(blank=True, default=0, null=True)),
                ('bodylikes', models.ManyToManyField(blank=True, related_name='bodylikes', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
