# Generated by Django 4.0.3 on 2023-03-30 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_bodyweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepietitle', models.CharField(max_length=200)),
                ('instructions', models.CharField(max_length=200)),
                ('preptime', models.CharField(max_length=200)),
                ('cooktime', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('tools', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
