# Generated by Django 4.0.3 on 2023-03-30 13:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recepies'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepies',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepies',
            name='recepievideo',
            field=models.FileField(default=1, upload_to='recepievideo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepies',
            name='viewss',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
