from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index,name="index"),
    path('services/',views.services,name="services"),
    path('signup/',views.signup,name="signup"),
    path('loggedin/',views.loggedin,name="loggedin"),
    path('logout/', views.Logout, name="logout"),
    path('uploadpost/',views.uploadpost,name="uploadpost"),
    path('uploadworkout/',views.uploadworkout,name="uploadworkout"),
    path('viewvideo/<int:id>/',views.viewvideo,name="viewvideo"),
    path('like/<int:id>/',views.like,name="like"),
    path('workouts/',views.workouts,name="workouts"),
    path('workoutsmonday/', views.workoutsmonday, name="workoutsmonday"),
    path('workoutstuesday/', views.workoutstuesday, name="workoutstuesday"),
    path('workoutswednesday/', views.workoutswednesday, name="workoutswednesday"),
    path('workoutsthursday/',views.workoutsthursday,name="workoutsthursday"),
    path('workoutsfriday/', views.workoutsfriday, name="workoutsfriday"),
    path('workoutssaturday/', views.workoutssaturday, name="workoutssaturday"),
    path('workoutssunday/', views.workoutssunday, name="workoutssunday"),
    path('arms/', views.arms, name="arms"),
    path('abscore/', views.abscore, name="abscore"),
    path('back/', views.back, name="back"),
    path('biceps/', views.biceps, name="biceps"),
    path('chest/', views.chest, name="chest"),
    path('triceps/', views.triceps, name="triceps"),
    path('legs/', views.legs, name="legs"),
    path('shoulders/', views.shoulders, name="shoulders"),
    path('bodyweightworkout/', views.bodyweightworkout, name="bodyweightworkout"),
    path('bodyweight/', views.bodyweight, name="bodyweight"),
    path('viewvideobodyweight/<int:id>/', views.viewvideobodyweight, name="viewvideobodyweight"),
    path('uploadrecepies/', views.uploadrecepies, name="uploadrecepies"),
    path('recepies/', views.recepies, name="recepies"),
    path('singlerecepies/<int:id>/', views.singlerecepies, name="singlerecepies"),
    path('userprofile/<int:id>/', views.userprofile, name="userprofile"),
    path('following/<int:id>/', views.following, name="following"),
    path('userprofilevid/<int:id>/', views.userprofilevid, name="userprofilevid"),
    path('listfollowers/<int:id>/', views.listfollowers, name="listfollowers"),
    path('loginprofile', views.loginprofile, name="loginprofile"),
    path('profileofollowers/<int:id>/',views.profileofollowers,name="profileofollowers"),
]